name: kohya-runtime
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      # Runtime-only / fast-changing deps
      - transformers
      - accelerate
      - diffusers
      - safetensors
      - huggingface_hub
      - datasets
      - einops
      - sentencepiece
      - tqdm
      - pyyaml
